upd

diff --git a/.github/workflows/cuda12.1-whl-release.yml b/.github/workflows/cuda12.1-whl-release.yml
--- a/.github/workflows/cuda12.1-whl-release.yml
+++ b/.github/workflows/cuda12.1-whl-release.yml
@@ -40,8 +40,22 @@ jobs:
           haskell: true
           large-packages: true
           swap-storage: false
+      - name: Set default values
+        id: set_defaults
+        run: |
+          echo "[INFO] Event name is '${{ github.event_name }}'"
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "REPO=${{ inputs.repo }}" >> $GITHUB_ENV
+            echo "BRANCH=${{ inputs.branch }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
+            echo "REPO=internLM/lmdeploy" >> $GITHUB_ENV
+            echo "BRANCH=main" >> $GITHUB_ENV
+          else
+            echo "[ERROR] Unsupported event '${{ github.event_name }}'." >&2
+            exit 1
+          fi
       - name: Checkout repository
-        run: git clone -b ${{ inputs.branch }} --depth=1 https://github.com/${{ inputs.repo }}
+        run: git clone -b ${{ env.BRANCH }} --depth=1 https://github.com/${{ env.REPO }}
       - name: Build
         run: |
           echo ${PYTHON_VERSION}
